//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingDifferent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int IDAccount { get; set; }
        public int Balance { get; set; }
        public string AccountOwner { get; set; }
    }
}
